# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6674282fc98df5e303df63aeffa9218731ccaac117f0ab1e15398a492410a8651e097db57d30b4cee573148aa98fcef7fc91dfde31f6850d70d1d85ac8488e7

test:
  secret_key_base: dcc799fb639edbe02ef2634e7b1eb5cf535583d2ef442ce276ca2625e4f958eb2e95ea93828bda4b11bdc311845d04b97d2054a1653cb238f2d1be8f5d167a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
